coverage:
  status:
    project:
      default:
        # GitHub status check is not blocking
        informational: true
    patch:
      default:
        # GitHub status check is not blocking
        informational: true
comment:
  # Only write a comment in PR if there are changes
  require_changes: true
